<?php

/**
 * @file
 * Primary module hooks for event_registration module.
 */

/**
 * Implements hook_mail().
 */
function event_registration_mail($key, &$message, $params) {
  switch ($key) {
    case 'registration_confirmation':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
  }
}
